services:
  web:
    image: fauria/vsftpd:latest
    environment:
      - FTP_USER=root
      - FTP_PASS=root
      - PASV_ADDRESS=0.0.0.0
      - PASV_ENABLE=YES
    networks:
      - rct_storage_backend
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    container_name: vftp_servers
    volumes:
      - rct_ftp_data:/home/vsftpd/

volumes:
  rct_ftp_data:


networks:
  rct_storage_backend:
    external: true
    driver: bridge
