services:
  web:
    image: fauria/vsftpd:latest
    environment:
      - FTP_USER=root
      - FTP_PASS=root
      - PASV_ADDRESS=0.0.0.0
      - PASV_ENABLE=YES
      - PASV_MIN_PORT=8091
      - PASV_MAX_PORT=8092
    network_mode: host
    container_name: vftp_servers
    volumes:
      - rct_ftp_data:/home/vsftpd/
      # 内网无法改变端口，需要注释掉下一行
      - /Users/tsinghuaboy/projects/rct-ftp/vsftpd.conf:/etc/vsftpd/vsftpd.conf

volumes:
  rct_ftp_data:


networks:
  rct_storage_backend:
    external: true
    driver: bridge
